<a href="https://colab.research.google.com/github/sammyGuru/Marvel-Level-1/blob/main/numpyarr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
array = ([[2,1],[3,4]])
repeat_array = np.tile(array,(3,4))#repeats the array 3 times in first dimension and 4 times in the second using np.tile()
print(repeat_array)

[[2 1 2 1 2 1 2 1]
 [3 4 3 4 3 4 3 4]
 [2 1 2 1 2 1 2 1]
 [3 4 3 4 3 4 3 4]
 [2 1 2 1 2 1 2 1]
 [3 4 3 4 3 4 3 4]]


In [5]:
shape = (4,3)
index = np.indices(shape)
print(index)
print()
flat_index = np.ravel_multi_index(index,shape)#converts multidimensional array into a flat array where indices are in ascending order
print(flat_index)#Each value in the flat_index array corresponds to the index of the element in the original array, with the order determined by flattening the index array.

[[[0 0 0]
  [1 1 1]
  [2 2 2]
  [3 3 3]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
